export const motivationalLines = [
    "You got this! 💪",
    "One step closer to healing. 🌟",
    "Keep fighting! 💊",
    "Your strength is unbreakable! 💥",
    "Stay strong, you're almost there! 🚀",
    "Healing starts with you. 🧡",
    "Every dose is progress. 🔥",
    "You're a warrior! 🏆",
    "Don't stop now! ✨",
    "Your journey to health is just beginning. 🌱",
    "Healing is a process, but you're strong. 💪",
    "Keep going, you are unstoppable! 💯",
    "Believe in your healing. 🌈",
    "You're more powerful than you know! ⚡",
    "Stay positive, stay strong! ✌️",
    "Your recovery is worth it. 💖",
    "You’re closer to your goal every day. 🎯",
    "Keep pushing forward! ⏩",
    "Strength is built with every step. 🚶‍♀️",
    "The best is yet to come. 🌟",
    "You're stronger with each dose! 💥",
    "Healing is your superpower. 🦸‍♂️",
    "Every moment counts. ⏳",
    "Small steps lead to big changes. 🏃‍♂️",
    "You’re doing amazing! 🌻",
    "Every day is a step toward better health. 🌞",
    "Keep going, you've got this! 💯",
    "Strength lies within you. 💪",
    "This is just a chapter. 📖",
    "Your health is your wealth. 💰",
    "The power to heal is within you. 🌿",
    "You're moving toward greatness! 🚀",
    "Your future is bright. 🌞",
    "You are a fighter! 🥊",
    "Success is in your future. 🎉",
    "Every challenge makes you stronger. 💪",
    "Healing takes time, but it's worth it. 🕰️",
    "You're a champion! 🏅",
    "This is your time to shine. ✨",
    "Keep pushing, the finish line is near! 🏁",
    "Your resilience is inspiring. 🌟",
    "You’ve got the strength to overcome anything. 💪",
    "Believe in your healing journey. 🌱",
    "Your health is your power. ⚡",
    "Keep your head up! 💫",
    "Every dose brings you closer to your best self. 🌟",
    "You are unstoppable. 🚀",
    "Stay positive, your breakthrough is near. 🌈",
    "Strength grows in the moments you keep going. 🌿",
    "Healing is a process, but you’re getting better. 💚",
    "You’re doing amazing things! 💥",
    "Keep pushing, your health is worth it. 💖",
    "You’ve got the power to heal. ✨",
    "Recovery is your next victory. 🏆",
    "Keep believing in yourself! 💫",
    "You are not alone in this. 🤝",
    "One day at a time. 🗓️",
    "You're doing incredible. 👏",
    "Trust the process. 💖",
    "The best days are ahead of you. 🌞",
    "You are on the right path. 🚶‍♀️",
    "Keep going, your strength is incredible! 💪",
    "You’re closer to healing every day. ⏳",
    "Your persistence will lead to greatness. 🌠",
    "Stay strong, the healing journey is worth it. 💯",
    "You’re capable of amazing things. 💫",
    "Success is just around the corner. 🏆",
    "One step closer to your goal. 🏁",
    "You're resilient and strong. 💪",
    "Every day brings you closer to healing. 🌞",
    "You're already doing great! 🌸",
    "You are capable of healing. 🌿",
    "Every step is progress. 🏃‍♀️",
    "Stay positive, stay strong! ✌️",
    "Believe in the power of healing. 💖",
    "Your journey is powerful. 🌟",
    "You are getting stronger with every dose. 💪",
    "Keep moving forward, you're doing great! 🚀",
    "Recovery is just around the corner. ⏳",
    "Healing is a journey, but you’re on the right track. 🛤️",
    "You’re unstoppable, keep going! 🚀",
    "You have the strength to heal. 💚",
    "The best is yet to come! 🌟",
    "You are a force to be reckoned with! ⚡",
    "Every day, you're one step closer. 🏁",
    "Keep fighting, your health is your wealth. 💪",
    "Recovery is just the beginning. 🌈",
    "You are more powerful than you realize. 💥",
    "Stay strong, your strength will lead you. 💪",
    "The power of healing is in your hands. 🌿",
    "You're a warrior in recovery. 🏆",
    "Every pill, every step, is part of your victory. 🏅",
    "You're on the path to greatness. 🌟",
    "Keep the faith, healing is happening. 🙏",
    "You’re healing, and that’s powerful. ✨",
    "Your strength knows no limits. 🌈",
    "This is your time to shine! 🌟",
    "You're getting better every day. ⏳",
    "Your determination is powerful! ⚡",
    "You're doing amazing, keep going! 💖",
    "Your health journey is worth every step. 🦋",
    "Healing is happening, keep going! 🌱",
    "You’ve got the power to overcome. 💪",
    "This moment is just a stepping stone. 🌱",
    "Stay strong, you're doing incredible things! 💥",
    "Your recovery story is powerful. 📖",
    "Healing takes time, but you're on the right path. 🛤️",
    "You're moving toward something great. 🌟",
    "Each dose is a reminder of your strength. 💊",
    "You’re stronger than you think! 💪"
  ];
  